### PR TITLE
Add license headers to files in private/

### PR DESCRIPTION
**Pull request by cbm755**
This is on top of PR #169.  

I tried to track changes back enough to give appropriate attribution.  Of course, it can be corrected if I've missed something/someone.

### CODE REVIEW

**Comment by cbm755** [comment]
I will rebase this on top of recent changes

**Comment by cbm755** [comment]
Oooh, you read my mind ;-)  Carry on...

**Comment by catch22** [comment]
Oh, sorry. 😄Done with the rebase & thanks for the changes. Please feel free to merge whenever you like.

By the way, what's the right way of updating the copyright notices? Add the current year whenever one makes a change to a file?

**Comment by catch22** [comment]
The newly added files in `private` are still missing copyright notices.

**Comment by cbm755** [comment]
Yes I try to update the year as I modify the file.  Commas if its discontinuous, or hyphenated for a range of years.

There seem to be various practices for all this:

* I like to use multiple copyright lines as I figure that gives maximal explicit credit.  It also shows exactly who you'd need to ask if you want a different license.
* New contributors to a file get added to the bottom of the list.
* whoever updates a file should add the year they update to the appropriate copyright line.  But should not re-order the lines.
* sometimes I don't update the year if I feel I'm making a minor "maintenance change" (whatever that means).

**Pull request merged**
