### PR TITLE
better doctest <dir> support

### PR DESCRIPTION
**Pull request by cbm755**
Improvement on my #84.

This looks like a big change, but mostly its just dumping some code from `doctest` to `doctestdrv.m` which can:
  1.  chdir if it gets a directory
  2.  call itself for directory contents.

Todo/decisions:
- [x] recursion support
- [x] recursion default on/off?  off for now, could easily revisit
- [x] better name for `doctestdrv`.  `doctestraw`?  its private so doesn't really matter.

Maybe more, but I think this is merge-able now.  @catch22 comments?

### CODE REVIEW

**Comment by catch22** [comment]
Thanks for your work on this.

How about doing the recursion in `doctest_collect` rather than in the new `doctestdrv` function?

**Comment by cbm755** [comment]
Ok, makes sense.  But now I should rename it from `doctest_collect`.  Maybe `doctest_core`?  `doctest_process`? something else

**Comment by catch22** [comment]
I was thinking that `doctest_collect` would still do just the collecting of test targets (including recursion into directories if that option is specified), while `doctest` runs the tests.

Was there some technical reason that led you to merge collection & executation?

**Comment by cbm755** [comment]
It was so that I could call chdir to descend into a directory, then call itself recursively on its contents.  I guess it just seems like a simpler design to me.

If I collect them all first, I need to make two traversals (once when collecting and then again when executing.  In practice, I need to record (at least) the path for each target.  I felt this leads to duplicated logic about e.g., class/functions in both the collect and run logic (both need to traverse directories for example).

Other than historical reasons, is there some advantage or feature enabled by collecting them all first?

**Comment by catch22** [comment]
I thought it was a nice "separation of concerns" to do the test collection and execution independently from each other. The plan that you sketched where you would record the path or working directory in the collection phase and have it used by the runner also sounds like a nice design to me (given that the collection logic alone was already somewhat complex even before the directory support).

However, I don't have a non-hypothetical use case that requires this design. As I also don't have a much time in the coming days to contribute anything useful please go ahead with whatever makes most sense to you right now - we can always refactor later on :smile:

**Comment by cbm755** [comment]
Ok, that sounds good to me.  I certainly don't mind if its refactored later.

But I'm not in any hurry if you prefer to wait?  Or should I go ahead and merge now?

**Comment by catch22** [comment]
Please go ahead and merge it.

**Pull request merged**
