### PR TITLE
Add test collection in directories (a la runtests and __run_test_suite__)

### PR DESCRIPTION
**Pull request by catch22**
How do you like the API? I am not sure about the usual Octave way of handling flags like `recursion`; is the boolean fine?

@oheim What would you like `logfile` to do? Print out all messages to some logfile but still report all individual PASS/FAILs on stdout?

### CODE REVIEW

**Comment by cbm755** [comment]
Re: testing a directory: I'm inclined to just have `doctest('.')` do this as that is more discoverable.  But I'm not sure about recursion.

I'm inclined to agree with @oheim's view of just having one function...

(Personally I never use Octave's `runtests` b/c it has no summary.  So its very hard to see what is happening if you have xfail's for example.)

**Comment by cbm755** [comment]
"... just one PUBLIC function" I should say

**Comment by catch22** [comment]
@cbm755 I took @oheim's view to mean that he wanted one function out of `runtests` and `__run_test_suite`. Perhaps I misunderstood? Personally I would also prefer to have a single `doctest` function that can work on directories, too.

If it is no longer a goal to adhere to Octave's test API then how about we go about an `inputParser` style interface with a `recursion` switch and an optional `logfile` parameter such as in the following:

~~~
doctest WHAT
doctest WHAT recursion
doctest WHAT logfile <filename>
doctest WHAT recursion logfile <filename>
~~~

**Comment by cbm755** [comment]
Yes I think that would be my preference.  @oheim can you clarify https://github.com/catch22/octave-doctest/issues/37#issuecomment-101759879?

But if we do have some sort of extra driver layer, then I agree just one please! :)

**Comment by oheim** [comment]
I meant having only one wrapper function instead of two. On the other side, having only one public function at all, i. e., no wrapper needed, would also be okay, unless it makes the call syntax ambiguous.

You should choose whatever solution is the easiest to maintain. If you can separate the recursion and log file code, it is wise to put that into a separate wrapper function. If the wrapper function does not add any value at all, because the recursion and logging must be implemented in `doctest` anyway, go without a wrapper.

If you plan to support a command syntax, make sure that you can clearly separate the options from the function/file names to be tested. Probably `doctest WHAT -recursion -logfile <filename>` is a better approach, cf. the function `pkg.m` in Octave core.

**Comment by catch22** [comment]
I like your suggested syntax and don't think it will lead to problems, so maybe we should go for this.

[Internally, `doctest` is already decoupled according to its phases (test collection, test execution, ...). The `evalc` workaround currently forces `doctest` to operate on multiple targets at once, precludes a proper decoupling of concerns a la `test`/`runtests`. I just saw your proposal for a proper `evalc` implementation. Nevertheless I would say that we should go for a single function if that does not lead to ambiguities.]

**Comment by catch22** [comment]
I'll take a crack at the new syntax.

**Comment by catch22** [comment]
It is becoming complicated to implement `doctest_collect` correctly, since there are many cases to consider and some decisions to be made. We should perhaps define the semantics together before starting to code it up. I'll add some more details some time in the coming days.

**Comment by cbm755** [comment]
@catch22 It also doesn't have to be perfect the first time.  For example, recursion could come later...

IMHO, executing a directory is important for 0.4.0.

**Comment by catch22** [comment]
Yes, I agree. I'm thinking we should extend `doctest_collect` to support directory targets (then recursion is simple once we can "recurse" into a single directory). I can propose a rough sketch of the design that I have in mind tonight & perhaps someone else could take it from there.

**Comment by cbm755** [comment]
I was not overly keen on the "absolute path" stuff.  But I read this and used the ideas here in #85.  There I call tests per file, as we get to them, rather than collecting them all ahead of time.  IMHO, this makes recursing into directories more intuitive.

**Comment by catch22** [comment]
Closing, as it was superseded by #84 and #85.

**Pull request closed without merging**
