### PR TITLE
texinfo: skip code blocks w/o output by default

### PR DESCRIPTION
**Pull request by cbm755**
This supercedes #119: it skips blocks without output by default only on texinfo.  It does add the directive, but its discreet about it (see test) and its not formally documented.

### CODE REVIEW

**Comment by cbm755** [comment]
oh heh, forgot to test `doctest doctest`: *sheepish*: I guess this doesn't interact well with our hybrid texinfo/diary style in `doctest.m` itself...  back to drawing board.

**Comment by cbm755** [comment]
This is closer, but when I ran it on Symbolic's doctest suite, I found three failures.  
````
%% @example
%% @group
%% n_orig = digits(7);
%% vpa('pi')
%%   @result{} (sym) 3.141593
%%
%% digits(42)
%% vpa('pi')
%%   @result{} (sym) 3.14159265358979323846264338327950288419717
%%
%% digits(n_orig)      % reset digits to saved value
%% @end group
%% @end example
````
Note the final line does not produce output and SKIP_BLOCKS_WO_OUTPUT activates---incorrectly because this `@example` block has some output.

Next idea: delete blocks with no output during parse_texinfo...

**Comment by cbm755** [comment]
Ok @catch22 this is ready!  It has no effect on diary mode.  It should have no effect on diary-mode within texinfo.  It adds tests, one of which is (sort of) documentation.

It fixes #113.

**Comment by catch22** [comment]
The `test_skip_wo_output.texinfo` test is quite wonderful :smile: 

With regards to the naming of `SKIP_BLOCKS_WO_OUTPUT`: Right now, I understand this is ignored in diary mode, which is completely fine for me. It makes me wonder though if the directive's name should contain `TEXINFO` (making it even more unwieldy to type :smile:)

Alternatively, we could make `SKIP_BLOCKS_WO_OUTPUT` work with diary-style tests, too, but default to "don't skip" in the latter case.

What do you think?

**Comment by cbm755** [comment]
I think I'll just rename it.  Its quite hard to get this to work reliably (note its not done through our directives system) mainly because of inconsistency in what "BLOCK" means...  Also complicated by the fact that texinfo and diary are not mutually exclusive.  I think if anyone wants this to work in diary mode, they can work on it---I'm a bit sick of this issue to be honest ;-)

**Comment by catch22** [comment]
Thanks for your work on this ;-)

**Comment by cbm755** [comment]
Ok if I merge?  (see also two other PRs that I think are ready).

**Comment by catch22** [comment]
Sure!

**Pull request merged**
