### PR TITLE
[decision needed] Drop green highlighting

### PR DESCRIPTION
**Pull request by cbm755**
Not necessarily intended for merge.

In case we do want to drop the green.  Would be good to have opinion from @oheim

### CODE REVIEW

**Comment by oheim** [comment]
3b399129b3ecf8fb1891de98a77aca5a818df6d4 throws a lot of warnings
    warning: terminal_escapes: some elements in list of return values are undefined

4673bb4e4262344bdcfe9e26600fed1215877052 produces an error: hiliteoff vs. hilite_off

I am using gnome-terminal with the solarized light color theme, which probably overrides the intended colors with something else.

If it was my decision, I would copy the behaviour of _run_test_suite_ in as many details as possible. That is, (1) no colors, (2) write failed doctests into doctest.log and not on console, (3) print the number of PASS/TOTAL for each file on stdout, (4) print the total number of PASS and FAIL on stdout, (5) do not mention files without example blocks on console, but add them in doctest.log.

    Integrated examples in documentation:
    
      …
      @infsupdec/vertcat .................... PASS    1/1
      …
      doc/chapter/advanced-topics.texinfo ... PASS   19/19
    
    Summary:
    
      PASS   326
      FAIL     0
    
    See the file doctest.log for additional details.
    
    65 (of 278) targets have no example blocks.

For details on the formatting please see _run_test_suite_.

**Comment by catch22** [comment]
Regarding (1), I would prefer colors by default but might be convinced otherwise if there is no way to detect when stdout is not a tty (cf. #33).

I am quite strongly against (2) as default options, as I am using `doctest` for interactive development and it is quite useful to see the error messages on the terminal right away (likewise for (5), but there the case is not quite as strong).

I would be very glad to adopt (3). Why do you propose a different format in (4) than in (3)?

On a higher level, would it be useful to make `doctest` a bit more modular so that `run_test_suite` (which I presume is Octave's internal test suite?!) could be a small wrapper around it that does all the reporting in the "non-interactive" fashion that you prefer?

**Comment by oheim** [comment]
The different format in (3) vs (4) is the current behaviour of `__run_test_suite__`. On the individual file level you can see the fraction of good tests for that file. The overall sum at the end divides that into PASSes and FAILs.

On the strategic level it would probably solve all other points easily if `doctest` would write failures to stdout (and possibly halt at the first error), whereas `__run_doctest_suite__` would write a log file and only give a summary. In Octave core the `test` function has a `'quiet'` and a `'normal'` switch for these different modes of operation.

**Comment by catch22** [comment]
@oheim @cbm755 Should `__run_doctest_suite__` be part of Octave and use some API provided by `doctest`, or do you think it should be a tool shipped in the doctest package?

**Comment by oheim** [comment]
If it is solely used to call doctest, put it in the package.

**Comment by cbm755** [comment]
> If it is solely used to call doctest, put it in the package.

I agree.

FWIW, I don't like the underscores at the beginning/end which imply internal private use (to me).  I assume this is for historical reasons in Octave (not sure of that).  But seems to me `run_doctest_suite` would be preferable.

**Comment by cbm755** [comment]
Some of what @oheim suggests might be more do-able after #6.  For example: I deliberately output the per-file summary *after* all processing all tests, so that the spammy output is self-contained and not interleaved with the summary of each file.

**Comment by oheim** [comment]
Yes, `run_doctest_suite` should be okay. Or you consider calling it `rundoctests` after the Octave function `runtests`. AFAIK, the only difference between `__run_test_suite__` and `runtests` is that the latter does not search test targets recursively and does not write a log file and summay at the end.

**Comment by catch22** [comment]
Let's continue the conversion in #37.

**Pull request closed without merging**
