### PR TITLE
Texinfo comments

### LINKED ISSUE #62: `@comment` support for texinfo docs
- [x] bits in `@comment` should not be tested (`@c` as well?), deal with in the extract code.
- [x] consider allowing the `doctest: +SKIP`` tag to be placed inside an @comment.

### PR DESCRIPTION
**Pull request by cbm755**
Fixes #62.

### CODE REVIEW

**Comment by cbm755** [comment]
@oheim what do you think?

**Comment by oheim** [comment]
Sorry, I didn't see the big picture. It makes sense to completely remove the `@comment`s, because they are on the meta level and not part of the code. I like your solution.

**Comment by cbm755** [comment]
Ok, don't merge yet, I will future-proof a bit...

**Comment by cbm755** [comment]
Thanks @oheim.   I'll take that as a +1 unless I hear otherwise.

**Pull request merged**
