### PR TITLE
Allow somewhat arbitrary code inside XFAIL_IF()

### PR DESCRIPTION
**Pull request by cbm755**

### CODE REVIEW

**Comment by catch22** [comment]
In some of my own code, I've found that it's more convenient to define nullary functions like [this one](https://github.com/catch22/quantbox/blob/master/sdp/solve_sdp_available.m) instead of repeating the same detection code in several doctests. However, it will still be very nice to be able to allow for arbitrary expressions in `XFAIL_IF` etc.!

I'll check the PR tonight. Just a quick question: Since regexp can't match arbitrarily nested parentheses I presume you have put an upper bound on them? Maybe that's worth mentioning/documenting.

**Comment by cbm755** [comment]
no, I just forbid newlines and the str "doctest:": it makes no attempt to check for nested bracket: I don't know how to do so.

If you write this:
````
a = 7    % doctest: +SKIP_IF(is_octave()) b = (7)
````
the directive will be: `is_octave()) b = (7`, to which I say: "you deserved it!".

**Comment by catch22** [comment]
I am currently using

% doctest: +SKIP_UNLESS(solve_sdp_sdpt3_available)   % doctest: +XFAIL   % sdpt3 bug

in quantbox, which would fail with the new parsing.

(Similar code in doctest's tests uses `% doctest: -NORMALIZE_WHITESPACE   % doctest: +XFAIL`.)

**Comment by catch22** [comment]
I suppose in my use case I could just reorder the two directives, as our directives currently commute. But this fix wouldn't be possible if someone had multiple `+SKIP_UNLESS(...)`/... directives in a single doctest? Hmm.

**Comment by cbm755** [comment]
Multiple doctest: directives per line/cmd is OK with this change!  Did I miss your point?  Maybe we need more test coverage for those cases?

**Comment by catch22** [comment]
Oh, great - I misinterpreted what you wrote!

In case this is an easy change, maybe it makes sense to also disallow "%", so that one can still document a doctest as in

~~~
>> ... % doctest: +SKIP_UNLESS(solve_sdp_sdpt3_available)   % sdpt3 bug
~~~

What do you think?

**Comment by cbm755** [comment]
That would work right now (b/c it looks for a closing parenthesis).

This might be a problem:
````
>> ... % doctest: +SKIP_UNLESS(solve_sdp_sdpt3_available)   % bug (maybe?)
````
Then I think the directive condition would parse as:
````
solve_sdp_sdpt3_available)   % bug (maybe?
````

> maybe it makes sense to also disallow "%"

But what if someone wants printf inside her directive condition?  `XFAIL_IF(strcmp(sprintf('%s', foo), bar))`.

I think unless we actually parse it (i.e., call some kind of parsing function, not write our own), then we'll always find some corner case.

**Comment by cbm755** [comment]
One thing approach would be to say `XFAIL_IF` doesn't have parentheses and instead the directive conditional is the remainder of the line:
````
>> ....  % doctest +SKIP_IF full_moon() && summer_solstice()
````
(But based on your re-world examples, looks like you would not want that!)

**Comment by cbm755** [comment]
Or we just decide our spec is going to be that these things are allowed:
````
% doctest +SKIP_IF (....)   % doctest +FOO (...)\n
% doctest +SKIP_IF (....)   % doctest +FOO\n
% doctest +SKIP_IF (....)\n
````
Whereas these give undefined behaviour:
````
% doctest: +SKIP_IF (....)  % some comment\n
% doctest: +SKIP_IF (....)  b = date ()\n
````
(i.e., you can put another `doctest:` on the line, but nothing else).

**Comment by catch22** [comment]
Would `% some comment % doctest: +SKIP_IF(...)` (i.e., ordinary comment before doctest comment) still work under your proposed scheme? I like to document the reasoning for skip'ed/xfail'ing doctests and adding an ordinary comment seemed idiomatic.

In general, the proposed algorithm makes me feel slightly uneasy (because of the corner cases that it will introduce) but it's hard for me to judge since I don't have use for the added functionality right now. So I think I'll defer to your judgement with regards to merging the PR!

PS: I just ran the PR on some quantbox tests and everything seemed to work fine.

**Comment by cbm755** [comment]
> Would |% some comment % doctest: +SKIP_IF(...)| (i.e., ordinary comment
> before doctest comment) still work under your proposed scheme?

yes, anything is ok *before* the first `% doctest:`.

Maybe I should add some more tests for these various cases you've mentioned.

> ran the PR on some quantbox tests and everything seemed to work fine.

Great news!

I understand your unease.  I'll sleep on this.

**Comment by cbm755** [comment]
I'll merge this.  Perhaps there are more edits to follow for corner cases but I think having this is somewhat inevitable once we added `XFAIL_IF` :-)

**Pull request merged**
