### PR TITLE
Improved Maintainer Makefile

### LINKED ISSUE #78: Fix hardcoded 'tmp' in Makefile.

### PR DESCRIPTION
**Pull request by oheim**
Fixed #78 and added targets for Octave package release

### CODE REVIEW

**Comment by catch22** [comment]
Thank you.

**Comment by cbm755** [comment]
I updated the wiki a bit b/c of this.

**Comment by oheim** [comment]
Please note that the exported package will be made from the current git revision, so you must check everything in beforehand.

You may also want to add a little more logic for the release process (see “dist” target in the interval package). However, I would not recommend automatic tagging or messing with git.

P.S. I have added a `.gitattributes` file, which excludes selected files from the release.

**Comment by oheim** [comment]
P.P.S. The comment “This may take a while” for the HTML generation can savely be removed ;) Since there are only two public functions, the generate_html packages is quickly done. For the interval package the process requires 2 minutes to finish on my machine.

**Comment by catch22** [comment]
:+1: for me. Please go ahead and merge if you are happy with it.

**Pull request merged**
