### PR TITLE
Classdef support

### PR DESCRIPTION
**Pull request by cbm755**

### CODE REVIEW

**Comment by cbm755** [comment]
This works on Matlab.  Some issues on Octave but there are not our issues... I'll file some issues for now...

**Comment by cbm755** [comment]
For the record, on Octave this does:
````
>> doctest test_classdef

test_classdef .......................................... NO TESTS
@test_classdef/amethod ................................. PASS    1/1   
@test_classdef/test_classdef ........................... NO TESTS

Summary:

   PASS    1/1   

3/3 targets passed, 2 without tests.
````

whereas on Matlab is does:
````
>> doctest test_classdef

test_classdef .......................................... PASS    2/2   
test_classdef.amethod .................................. PASS    1/1   
test_classdef.disp ..................................... PASS    1/1   
test_classdef.test_classdef ............................ PASS    1/1   

Summary:

   PASS    5/5   

4/4 targets passed, 0 without tests.
````

But I don't think any of these are our fault...

**Comment by cbm755** [comment]
@catch22 can I merge this?

**Comment by catch22** [comment]
Yes absolutely. Thanks!

**Pull request merged**
